### ISSUE TITLE
add surveys for all planets

### ISSUE THREAD

**Issue by CCBBatUT** [CCBBatUT/WolfmanDraculaCollaboration#4]
Add the text files for each planet to the planet subdirectory

**Comment by raynamharris** [comment]
I added mars.txt https://github.com/CCBBatUT/WolfmanDraculaCollaboration/pull/3

**Comment by raynamharris** [comment]
Aubregy fixed this in commit https://github.com/CCBBatUT/WolfmanDraculaCollaboration/pull/11

**Comment by caitlinfriesen** [comment]
I added venus #13
